name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Install cargo-binstall for rust project binary installation
        run: cargo install cargo-binstall
      - name: Install tre for dumping dir contents, tarpaulin for code coverage
        run: cargo binstall cargo-tarpaulin tre
      - name: Run tre
        run: tre
      - name: Run with code coverage
        run: cargo tarpaulin
